import type { Exercise } from "./types";

export const SEED_EXERCISES: Exercise[] = [
  {
    id: "ex-90-90-hip",
    name: "90/90 Hip Rotation",
    category: "Mobility",
    description: "Seated hip mobility drill that opens internal and external rotation through the hips, offloading rotational stress from the knee.",
    demo: [
      "Sit on the floor with one leg bent in front at 90°, the other behind at 90°.",
      "Keep the chest tall and both sit-bones grounded.",
      "Slowly rotate the torso and knees to switch sides under control.",
      "Pause briefly in each position; breathe steadily.",
    ],
    defaultPrescription: "2 × 8 switches per side",
  },
  {
    id: "ex-quad-roll",
    name: "Quad Roll (rolling pin on towel)",
    category: "Mobility",
    description: "Self-myofascial release for the quadriceps using a rolling pin over a towel to reduce tension pulling on the patella.",
    demo: [
      "Lie face-down with a towel folded over the front of the thigh.",
      "Place a rolling pin on top of the towel.",
      "Slowly roll from just above the knee to the hip crease.",
      "Pause on tender spots for 10–20 seconds; avoid the kneecap itself.",
    ],
    defaultPrescription: "2 minutes per leg",
  },
  {
    id: "ex-tke",
    name: "Terminal Knee Extension",
    category: "Activation",
    description: "Targets the VMO and reinforces full knee extension — essential for patellar tracking and gait.",
    demo: [
      "Loop a band around a sturdy anchor at knee height and around the back of the knee.",
      "Step back to create tension; the band pulls the knee into slight flexion.",
      "Press the knee back to lock out, squeezing the quad hard.",
      "Hold the locked position for 1–2 seconds, then return slowly.",
    ],
    defaultPrescription: "3 × 12 reps",
  },
  {
    id: "ex-wall-sit",
    name: "Wall Sit, Shallow (above 90°)",
    category: "Strength",
    description: "Isometric quad and glute loading at a shallow angle — builds capacity without irritating the patellofemoral joint.",
    demo: [
      "Stand with your back flat against a wall, feet hip-width and forward.",
      "Slide down only until knees are slightly bent — stay above 90°.",
      "Press the lower back into the wall and brace the core.",
      "Hold steady; breathe normally throughout.",
    ],
    defaultPrescription: "3 × 30s hold",
  },
  {
    id: "ex-side-abduction",
    name: "Side-Lying Hip Abduction",
    category: "Activation",
    description: "Wakes up the gluteus medius to control femoral rotation and reduce valgus collapse at the knee.",
    demo: [
      "Lie on your side with legs stacked and straight.",
      "Keep the top hip slightly rotated forward (toes down a touch).",
      "Lift the top leg straight up without rolling backward.",
      "Lower with control; keep tension on the side glute.",
    ],
    defaultPrescription: "2 × 15 reps per side",
  },
  {
    id: "ex-sl-bridge",
    name: "Single-Leg Glute Bridge",
    category: "Strength",
    description: "Unilateral posterior-chain strength to balance load between hip and knee.",
    demo: [
      "Lie on your back, one foot flat, the other leg extended.",
      "Press through the planted heel and lift hips into a straight line.",
      "Keep the pelvis level — don't let it drop on the free side.",
      "Lower slowly under control.",
    ],
    defaultPrescription: "3 × 10 reps per side",
  },
  {
    id: "ex-bridge-heel-dig",
    name: "Glute Bridge with Heel Dig",
    category: "Activation",
    description: "Engages the hamstrings and glutes together to support the knee from behind.",
    demo: [
      "Lie on your back with knees bent ~90°, feet flat.",
      "Drive heels firmly down into the floor (don't lift yet).",
      "Now lift the hips into a bridge, keeping the heel pressure.",
      "Pause at the top, squeeze, then lower with control.",
    ],
    defaultPrescription: "3 × 12 reps",
  },
  {
    id: "ex-sl-balance-towel",
    name: "Single-Leg Balance on Folded Towel",
    category: "Stability",
    description: "Trains ankle, knee, and hip proprioception together on an unstable surface.",
    demo: [
      "Fold a towel into a small pad on the floor.",
      "Stand on it with one foot, slight knee bend.",
      "Find a quiet focal point and keep the kneecap pointing forward.",
      "Hold steady; progress by closing the eyes briefly.",
    ],
    defaultPrescription: "3 × 30s per side",
  },
  {
    id: "ex-quad-stretch",
    name: "Standing Quad Stretch",
    category: "Mobility",
    description: "Lengthens the quadriceps and hip flexors to reduce anterior knee tension.",
    demo: [
      "Stand tall, holding a wall for balance if needed.",
      "Bend one knee and grasp the ankle behind you.",
      "Tuck the pelvis slightly under to feel a stretch in the front of the thigh.",
      "Keep the knees close together; breathe and hold.",
    ],
    defaultPrescription: "2 × 30s per side",
  },
  {
    id: "ex-figure-four",
    name: "Supine Figure Four",
    category: "Mobility",
    description: "Opens the deep hip rotators and glutes, releasing referred tension that affects knee tracking.",
    demo: [
      "Lie on your back with knees bent.",
      "Cross one ankle over the opposite thigh, just above the knee.",
      "Reach through and pull the bottom thigh toward your chest.",
      "Keep the head and shoulders relaxed on the floor.",
    ],
    defaultPrescription: "2 × 45s per side",
  },
];
